---
- name: Setup master
  hosts: master
  become: yes
  remote_user: gcp

  tasks:
    - name: Start locust master
      docker_container:
        name: locust_master
        image: hamza13/loadgen2
        state: started
        pull: yes
        expose:
          - 8089
        ports:
          - "8089:8089"
          - "5557:5557"
        env:
          FRONTEND_ADDR: "{{ lookup('env','FRONTEND_ADDR') }}"
          USERS: "750"
        command:
          - "locust"
          - "--master"
          - "--headless"
          - "--expect-workers={{ lookup('env', 'WORKER_NO') }}"
          - "--host={{ lookup('env','FRONTEND_ADDR') }}"
          - "--users={{ lookup('env','USER_NO') }}"
          - "--spawn-rate=5"
          - "--csv=/tmp/locust"
          - "--csv-full-history"
          - "--html=/tmp/report.html"
        mounts:
          - source: /home/gcp
            target: /tmp
            type: bind

    - name: Start stats handler
      docker_container:
        name: stats_handler
        image: hamza13/statshandler:0.1.3
        state: started
        pull: yes
        env:
          BUCKET_NAME: perfstats-cloud
          PROJECT_ID: cloudproject-404707
        mounts:
          - source: /home/gcp
            target: /tmp
            type: bind
