# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-restored
spec:
  instances: 1

  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi

  bootstrap:
    recovery:
      source: cluster-example

  externalClusters:
    - name: cluster-example
      barmanObjectStore:
        destinationPath: gs://persistancy
        googleCredentials:
          applicationCredentials:
            name: backup-creds
            key: gcsCredentials
        wal:
          maxParallel: 8

