---
apiVersion: v1
data:
  username: bG9nCg==
  password: bG9nCg==
kind: Secret
metadata:
  name: cluster-example-2-log
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-2
spec:
  instances: 3

  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: "gs://persistancy"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials

  managed:
    roles:
    - name: log
      ensure: present
      login: true
      superuser: false
      createdb: true
      passwordSecret:
        name: cluster-example-2-log
      inRoles:
        - pg_read_all_data
        - pg_write_all_data
