// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log/log.proto

package orderlog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Reply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Entry)(nil), "orderlog.Entry")
	proto.RegisterType((*Reply)(nil), "orderlog.Reply")
}

func init() { proto.RegisterFile("log/log.proto", fileDescriptor_41e0d72543c57a28) }

var fileDescriptor_41e0d72543c57a28 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc9, 0x4f, 0xd7,
	0xcf, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2f, 0x4a, 0x49, 0x2d,
	0xca, 0xc9, 0x4f, 0x57, 0x52, 0xe4, 0x62, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x92, 0xe0, 0x62,
	0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x95, 0xc4, 0xb9, 0x58, 0x83, 0x52, 0x0b, 0x72, 0x2a, 0x85, 0xf8, 0xb8, 0x98, 0xf2, 0xb3, 0xc1,
	0xb2, 0x1c, 0x41, 0x4c, 0xf9, 0xd9, 0x46, 0xc6, 0x5c, 0x6c, 0x3e, 0xf9, 0xe9, 0xe9, 0xa9, 0x45,
	0x42, 0x9a, 0x5c, 0xcc, 0x3e, 0xf9, 0xe9, 0x42, 0xfc, 0x7a, 0x30, 0x73, 0xf5, 0xc0, 0x86, 0x4a,
	0x21, 0x09, 0x80, 0x8d, 0x50, 0x62, 0x70, 0x52, 0x8d, 0x52, 0x4e, 0xcf, 0x2c, 0xc9, 0x28, 0x4d,
	0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x48, 0xcc, 0xad, 0x4a, 0xd4, 0x4d, 0xca, 0x2f, 0x4d, 0xc9,
	0x2f, 0x4d, 0xce, 0x48, 0xd5, 0x87, 0x29, 0x4f, 0x62, 0x03, 0x3b, 0xd4, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x67, 0xc6, 0x18, 0xb1, 0xb9, 0x00, 0x00, 0x00,
}
